spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: a9da91ae3a0e7ea6230d
            client-secret: 821296802c08a110391f092f52076c64b6ca0900
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: catalog-service-route
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
        - id: movie-service-route
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: series-service-route
          uri: lb://series-service
          predicates:
          - Path=/series/**
      default-filters:
        - TokenRelay
server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'