server:
  port: ${PORT:8082}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: series-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: series