server:
  port: ${PORT:8072}
eureka:
  client:
    service-url:
      defaultZone: http://localhost/eureka
   #  defaultZone: http://service-registry/eureka
spring:
  #security:
  #  oauth2:
  #    resourceserver:
  #      jwt:
  #        issuer-uri: https://accounts.google.com
  rabbitmq:
    username: guest
    password: guest
    host: localhost
  # host: rabbitmq
    port: 5672
  zipkin:
    base-url: http://localhost:9411/
 #  base-url: http://zipkin:9411/
    enabled: true
  application:
    name: series-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: series

queue:
  serie:
    name: SerieQueue