server:
  port: ${PORT:8072}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  application:
    name: series-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: series

queue:
  serie:
    name: SerieQueue