server:
  port: ${PORT:8761}

eureka:
  server:
    enableSelfPreservation: false
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true